### PR TITLE
Adding a test of the ratio for interesting case.

### PR DESCRIPTION
**Pull request by drvinceknight**

### CODE REVIEW

**Comment by geraintpalmer** [comment]
I won't merge this as the recent refactor will make it complicated. I'll just write it in myself, that ok?

**Comment by drvinceknight** [comment]
:+1:

**Comment by geraintpalmer** [comment]
Implemented in commit 11fed47182bf9052f5afcf3b2f9657d0cb4e105e instead.
Thanks @drvinceknight !

**Comment by drvinceknight** [comment]
:+1:

**Pull request closed without merging**
